name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:password@localhost:5432/test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.6" # change if using a different version

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Set up database
        run: |
          ruby bin/rails db:create
          ruby bin/rails db:schema:load

      - name: Run tests
        run: bundle exec rspec

      - name: Run Brakeman
        run: ruby bin/brakeman --no-pager

      - name: Run RuboCop
        run: bundle exec rubocop
